---
# call me with --extra-vars "myuser=foo myghuser=foogh"

- hosts: all
  become: true

  vars:
    homedir: "/home/{{myuser}}"

  tasks:

    - name: update apt cache
      apt: update_cache=yes
      tags:
        - packages

    - name: installs essential tools
      apt: name={{item}} state=installed
      with_items:
        - vim-nox
        - sudo
        - tmux
        - build-essential
        - git
        - python
        - python-pip
        - zsh
      tags:
        - packages

## sudo

    - name: make sudo group passwordless
      blockinfile:
        dest: /etc/sudoers
        block: |
          %sudo ALL=(ALL) NOPASSWD: ALL

## create the user

    - name: user add
      user:
        name: "{{myuser}}"
        groups: sudo
        shell: /usr/bin/zsh

## shell

    - name: fetch dotfiles
      git:
        repo: https://github.com/iMilnb/dotfiles.git
        dest: "{{homedir}}/etc/dotfiles"

    - name: link dotfiles
      file:
        src: "{{homedir}}/etc/dotfiles/{{item}}"
        dest: "{{homedir}}/{{item|regex_replace('^_', '.')}}"
        state: link
        force: yes
      with_items:
        - "_zshrc"
        - "_p9krc"
        - "_profile"
        - "_tmux.conf"
        - "_vimrc"
        - "_vim/colors/molokai-trans.vim"
      tags:
        - dotfiles

    - name: fetch oh-my-zsh
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: "{{homedir}}/.oh-my-zsh"

    - name: fetch powerlevel9k
      git:
        repo: https://github.com/bhilburn/powerlevel9k.git
        dest: "{{homedir}}/.oh-my-zsh/themes/powerlevel9k"

    - name: install vundle
      git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: "{{homedir}}/.vim/bundle/Vundle.vim"

## chown user

    - name: create .ssh directory
      file:
        path: "{{homedir}}/.ssh"
        state: directory
        mode: 0700

    - name: fetch SSH pubkeys
      get_url:
        url: "https://github.com/{{myghuser}}.keys"
        dest: "{{homedir}}/.ssh/authorized_keys"
        mode: 0600

    - name: chown user
      file:
        path: "{{homedir}}"
        owner: "{{myuser}}"
        recurse: yes
