---

- hosts: all
  become_method: su

  vars:
    vimrc: |
      syntax on
      set ts=8
      set noai
      set ruler
      set tw=80
      set t_Co=256
      colorscheme molokai-transparent
      set laststatus=2

    loadpowerline: |
      powerline-daemon -q
      POWERLINE_BASH_CONTINUATION=1
      POWERLINE_BASH_SELECT=1

    home: "{{lookup('env', 'HOME')}}"

  tasks:
    - name: installs essential tools
      apt: name={{item}} state=installed
      with_items:
        - vim-nox
        - sudo
        - tmux
        - build-essential
        - git
        - python
        - python-pip
      become: true

## sudo

    - name: make sudo group passwordless
      blockinfile:
        dest: /etc/sudoers
        block: |
          %sudo ALL=(ALL) NOPASSWD: ALL
      become: true

## shell

    - name: install powerline from pip
      pip: name=powerline-status
      become: true

    - file:
        path: "{{home}}/.profile.d"
        state: directory
        mode: 0755

    - name: record module path
      command: python -c "import powerline, os; print(os.path.dirname(powerline.__file__))"
      register: powerlinepath
      failed_when: powerlinepath is undefined

    - name: create powerline autoload
      copy: content="{{loadpowerline}}\n. {{powerlinepath.stdout_lines[0]}}/bindings/bash/powerline.sh\n" dest="{{home}}/.profile.d/powerline"

    - name: append profile.d autoload
      blockinfile:
        dest: "{{home}}/.profile"
        block: |
          [ -d ~/.profile.d ] && for s in ~/.profile.d/*;do . $s; done

## vim

    - name: fetch vim themes
      git:
        repo: https://github.com/hugoroy/.vim
        dest: "{{home}}/.vim"

    - name: create basic vimrc
      copy: content="{{vimrc}}\nset rtp+={{powerlinepath.stdout_lines[0]}}/bindings/vim\n" dest="{{home}}/.vimrc"

